### ISSUE TITLE
Umbrella: Set up separate windows server for activemq

### ISSUE THREAD

**Issue by lottiegreenwood** [mantidproject/autoreduce#323]
- [x] Get windows server from IT Service desk
- [ ] set up activemq (https://github.com/mantidproject/autoreduce/issues/107)
- [x] set up nagios monitoring (https://github.com/mantidproject/autoreduce/issues/322)
- [x] update documentation for activemq, including hawtio set up (ideally have this clearly differentiated from back end set up
